package com.itplace.userapi.recommend.trace;

public enum RecommendationEventType {
    RECOMMENDATION_REQUEST,
    RECOMMENDATION_IMPRESSION,
    RECOMMENDATION_CLICK,
    SEARCH_SUBMIT,
    SEARCH_RESULT_IMPRESSION,
    SEARCH_RESULT_CLICK,
    BENEFIT_DETAIL_VIEW,
    FAVORITE_ADD,
    FAVORITE_REMOVE,
    BENEFIT_USE,
    QUESTION_ASK,
    QUESTION_RESULT_CLICK,
    DISMISS,
    SKIP,
    FEEDBACK_POSITIVE,
    FEEDBACK_NEGATIVE
}
