name: CD - Deploy to OCI

on:
  workflow_run:
    workflows: CI - Build and Push Docker Image
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.OCI_SSH_HOST }}
          username: ${{ secrets.OCI_SSH_USER }}
          key: ${{ secrets.OCI_SSH_PRIVATE_KEY }}
          script: |
            # GitHub Secrets에 저장된 ENV 변수 전체를 서버에 .env 파일로 생성합니다.
            echo "${{ secrets.ENV }}" > .env

            # docker-compose.yml에 명시된 서비스의 최신 이미지를 받아옵니다.
            docker-compose pull

            # .env 파일을 참조하여 컨테이너를 백그라운드에서 실행합니다.
            docker-compose up -d --remove-orphans

            # 사용되지 않는 Docker 이미지를 정리하여 서버 용량을 확보합니다.
            docker image prune -f